name: Dev build

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      build_env: dev
      release_branch: release-dev
    secrets: inherit
