name: Prod build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    uses: ./.github/workflows/build.yml
    with:
      build_env: prod
      release_branch: release-production
    secrets: inherit
