name: UAT build

on:
  pull_request:
    branches:
      - uat

jobs:
  build:
    permissions:
      contents: write
    uses: ./.github/workflows/build.yml
    with:
      build_env: dev
      release_branch: release-uat
    secrets: inherit
